[build]
target="wasm32-wasip1-threads"

[target.wasm32-wasip1-threads]
runner = "/Users/rashsul/Desktop/ignite-mac/bin/ignition --log-level=ALL:INFO --local-wasm-path="
# runner = "/Users/rashsul/RustroverProjects/wasmedge_wasi_socket/iwasm --log-level=ALL:INFO --local-wasm-path="